// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPzZN2HSwfCotD-ieTo4c9pgE1KPJsC4w',
    appId: '1:195328342143:web:308ebb1f5cf619d53f674a',
    messagingSenderId: '195328342143',
    projectId: 'fbfitnessapp',
    authDomain: 'fbfitnessapp.firebaseapp.com',
    storageBucket: 'fbfitnessapp.firebasestorage.app',
    measurementId: 'G-9YYYSS5H9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKoWWjDdfLrpuSJIk3ueuNmrZzZgG7EMs',
    appId: '1:195328342143:android:09d42d3a742fdaa83f674a',
    messagingSenderId: '195328342143',
    projectId: 'fbfitnessapp',
    storageBucket: 'fbfitnessapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_jCt8kEONqEkYpqLz_sMx5eDbIz0HO5Y',
    appId: '1:195328342143:ios:5a102632d70a184b3f674a',
    messagingSenderId: '195328342143',
    projectId: 'fbfitnessapp',
    storageBucket: 'fbfitnessapp.firebasestorage.app',
    iosBundleId: 'com.example.fbfitnessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_jCt8kEONqEkYpqLz_sMx5eDbIz0HO5Y',
    appId: '1:195328342143:ios:5a102632d70a184b3f674a',
    messagingSenderId: '195328342143',
    projectId: 'fbfitnessapp',
    storageBucket: 'fbfitnessapp.firebasestorage.app',
    iosBundleId: 'com.example.fbfitnessapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPzZN2HSwfCotD-ieTo4c9pgE1KPJsC4w',
    appId: '1:195328342143:web:868cfaf6806982103f674a',
    messagingSenderId: '195328342143',
    projectId: 'fbfitnessapp',
    authDomain: 'fbfitnessapp.firebaseapp.com',
    storageBucket: 'fbfitnessapp.firebasestorage.app',
    measurementId: 'G-0W5Q8LV292',
  );
}
